import "./globals.css";
import { configureGenkit } from "@genkit-ai/core";
import { vertexAI } from '@genkit-ai/vertexai';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

configureGenkit({
  plugins: [
    vertexAI({
      projectId: process.env.GOOGLE_CLOUD_PROJECT_ID,
      location: "europe-west2"
    }),
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
